
spring:
  application:
    name: 'springcloudgateway'

server:
  port: 11506

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'