
spring:
  application:
    name: 'info-cadastral-service'
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/info_cadastral_service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true'
    username: 'root'
    password: 'root'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
  jpa:
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    hibernate.ddl-auto: 'update'
    generate-ddl: 'true'
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
  rabbitmq:
    host: 'localhost'
    port: '5672'
    username: 'admin'
    password: 'admin'

server:
 port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

security:
  oauth2:
    resource:
      user-info-uri: 'http://localhost:8083/user'

