
spring:
  application:
    name: 'info-cadastral-service'
  rabbitmq:
    host: 'localhost'
    port: '5672'
    username: 'admin'
    password: 'admin'

server:
 port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

security:
  oauth2:
    resource:
      user-info-uri: 'http://localhost:8083/user'

